# 1. Push Wayland variables to BOTH DBus and Systemd simultaneously
exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway

# 2. Announce that Sway is fully loaded (triggers Sunshine, Waybar, etc.)
exec systemctl --user start sway-session.target

# Headless/Server stuff
exec clipse --listen
exec swayosd-server
exec musicpresence
exec kdeconnectd
exec lxpolkit
exec swaync

# Desktop Apps
exec waybar
exec feishin
exec vesktop
exec zen-browser

# Notification "daemons"
exec ~/.config/sway/scripts/notifiers/bluetooth_notifier.sh
