exec "systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP && dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway && systemctl --user start sway-session.target"

# Headless/Server stuff
exec swayosd-server
exec musicpresence
exec kdeconnectd
exec lxpolkit
exec swaync
exec clipse -listen

# Desktop Apps
exec feishin
exec vesktop
exec zen-browser

# Notification "daemons"
exec ~/.config/sway/scripts/notifiers/bluetooth_notifier.sh
